### ISSUE TITLE
Error Uploading metadata file

### ISSUE THREAD

**Issue by msilikale05** [jlungo/geonodera#1]
`AttributeError at /layers/upload 'NoneType' object has no attribute 'charset' Request Method: POST Request URL: https://geonode.resilienceacademy.ac.tz/layers/upload Django Version: 1.11.20 Python Executable: /usr/local/bin/uwsgi Python Version: 2.7.14 Python Path: ['.', '', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux2', `

**Comment by olljal** [comment]
I find two different errors on django log file that might both be related:

```
[pid: 192|app: 0|req: 3677/14082] 10.42.226.215 () {52 vars in 1047 bytes} [Mon Mar 11 08:26:57 2019] GET /upload/progress => generated 17 bytes in 4 msecs (HTTP/1.1 200) 8 headers in 288 bytes (1 switches on core 1)
Invalid Layers. Needs an authoritative SRID in its CRS to be accepted
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/layers/views.py", line 214, in layer_upload
    metadata_upload_form=form.cleaned_data["metadata_upload_form"])
  File "/usr/src/geonode/geonode/layers/utils.py", line 498, in file_upload
    bbox_x0, bbox_x1, bbox_y0, bbox_y1, srid = get_bbox(filename)
  File "/usr/src/geonode/geonode/layers/utils.py", line 373, in get_bbox
    "Invalid Layers. "
GeoNodeException: Invalid Layers. Needs an authoritative SRID in its CRS to be accepted
Internal Server Error: /layers/upload
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/src/geonode/geonode/layers/views.py", line 297, in layer_upload
    out[_k] = out[_k].decode(saved_layer.charset).encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'charset'
```

and:
```
[pid: 129|app: 0|req: 8543/35342] 10.42.226.215 () {50 vars in 1095 bytes} [Tue Mar 12 12:36:25 2019] GET /upload/progress => generated 17 bytes in 5 msecs (HTTP/1.1 200) 8 headers in 288 bytes (1 switches on core 1)
Unsupported metadata format
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/layers/views.py", line 214, in layer_upload
    metadata_upload_form=form.cleaned_data["metadata_upload_form"])
  File "/usr/src/geonode/geonode/layers/utils.py", line 536, in file_upload
    identifier, vals, regions, keywords = set_metadata(xml_file)
  File "/usr/src/geonode/geonode/layers/metadata.py", line 65, in set_metadata
    raise RuntimeError('Unsupported metadata format')
RuntimeError: Unsupported metadata format
Internal Server Error: /layers/upload
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/src/geonode/geonode/layers/views.py", line 297, in layer_upload
    out[_k] = out[_k].decode(saved_layer.charset).encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'charset'
```

**Comment by olljal** [comment]
first one looks like this (and is same as UTU version is getting a lot):
https://github.com/GeoNode/geonode/issues/4188
